#include "global.h"

SDL_Window* window = NULL;
SDL_Renderer* renderer = NULL;
SDL_Event event;
SDL_Point mouse;
int gametype;
int type;
bool quit = false;
bool Pause = false;
bool Start = false;
bool isChoose = false;
bool isHi = false;
bool isInf = false;
fstream highscore;
vector<int> rating;

Text Score(5, 5, 50, 100, 1);
Text Round(SCREEN_WIDTH / 2 - 175, SCREEN_HEIGHT / 2 - 40, 80, 350, 1);
Text GameOver1(SCREEN_WIDTH / 2 - 175, SCREEN_HEIGHT / 2 - 100, 80, 350, 1);
Text GameOver2(SCREEN_WIDTH / 2 - 175, SCREEN_HEIGHT / 2 - 100, 80, 350, 1);

Mix_Music* cover = NULL;
Mix_Chunk* p_shot1 = NULL;
Mix_Chunk* skillE = NULL;
Mix_Chunk* skillQ = NULL;
Mix_Chunk* p_shot2 = NULL;
Mix_Chunk* explo_sound = NULL;
Mix_Chunk* shield_hit = NULL;
Mix_Chunk* picked = NULL;
Mix_Chunk* asteroid = NULL;

SDL_Texture* menu = NULL;
SDL_Texture* game_exit = NULL;
SDL_Texture* start = NULL;
SDL_Texture* mode1P = NULL;
SDL_Texture* mode2P = NULL;
SDL_Texture* back = NULL;
SDL_Texture* pauseheader = NULL;
SDL_Texture* pausewindow = NULL;
SDL_Texture* replay = NULL;
SDL_Texture* game_quit = NULL;
SDL_Texture* game_continue = NULL;
SDL_Texture* record = NULL;
SDL_Texture* rec_but = NULL;
SDL_Texture* rec_header = NULL;
SDL_Texture* info_header = NULL;
SDL_Texture* inf_but = NULL;
SDL_Texture* info = NULL;
SDL_Rect rec_header_rect;
SDL_Rect rec_but_rect;
SDL_Rect inf_header_rect;
SDL_Rect inf_but_rect;
SDL_Rect exit_rect;
SDL_Rect start_rect;
SDL_Rect mode1P_rect;
SDL_Rect mode2P_rect;
SDL_Rect back_rect;
SDL_Rect pauseheader_rect;
SDL_Rect pausewindow_rect;
SDL_Rect replay_rect;
SDL_Rect game_quit_rect;
SDL_Rect game_continue_rect;

SDL_Texture* bgr[2];
SDL_Texture* scorebar = NULL;
SDL_Texture* explo = NULL;
SDL_Texture* gameover = NULL;
SDL_Texture* life_bar = NULL;
SDL_Texture* energy = NULL;
SDL_Rect scorebar_rect;
SDL_Rect lifebar_rect;
SDL_Rect energy_rect;
SDL_Rect explo_rect;
int score = 0;
int level = 1;
bool check = true;
int cnt = 0;
int curframe_ex = 0;
int curframe_blood = 0;
int curframe_energy = 10;

SDL_Texture* shield_pickup = NULL;
SDL_Texture* shield = NULL;
SDL_Rect shield_rect;
SDL_Rect shieldpickup_rect;
int curframe_shield = 0;
bool isShield = false;
Timer shield_wait;
Timer shield_time;
Timer Shield;
int x_pos, y_pos;

SDL_Texture* f_asteroid = NULL;
SDL_Texture* d_astoroid = NULL;
SDL_Rect f_asteroid_rect;
SDL_Rect d_asteroid_rect;
int curframe_asteroid = 7;
bool isDes = false;
Timer asteroid_wait;
int x_start = SCREEN_WIDTH - 300;
int y_start;
double directA;
double angle = 0;
int wait_time = rand() % 10000 + 5000;

SDL_Texture* heal_pickup = NULL;
SDL_Rect heal_rect;
int curframe_heal = 0;
bool isHeal = false;
Timer heal_wait;
Timer heal_time;
int x_heal, y_heal;

SDL_Texture* creep[2];
SDL_Texture* boss[2];
SDL_Texture* creep_bul[2];
SDL_Texture* boss_bul[2];
SDL_Texture* p_img[3];
SDL_Texture* p_shot[2];
SDL_Texture* e_flame[2];
SDL_Texture* p_sup;
SDL_Texture* p_sup_bul;
SDL_Texture* p_engine;
SDL_Texture* mouse_img;